#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=ring;size=8;add_cosmetic=true", "id=scroll;size=2;add_cosmetic=true", "id=charm;size=5;add_cosmetic=true", "id=head;size=2;add_cosmetic=true", "id=necklace;size=3;add_cosmetic=true", "id=belt;size=3;add_cosmetic=true", "id=feet;size=3;add_cosmetic=true", "id=accessory;size=3;add_cosmetic=true", "id=body;size=2;add_cosmetic=true"]

